import uuid

from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.photo import Photo


async def get_photo(session: AsyncSession, photo_id: uuid.UUID) -> Photo | None:
    return await session.get(Photo, photo_id)


async def count_photos_for_event(session: AsyncSession, event_id: uuid.UUID) -> int:
    stmt = select(func.count()).select_from(Photo).where(Photo.event_id == event_id)
    result = await session.execute(stmt)
    return result.scalar_one()


async def create_photos(
    session: AsyncSession,
    *,
    event_id: uuid.UUID,
    uploader_id: uuid.UUID,
    photos: list[tuple[uuid.UUID, str]],
) -> list[Photo]:
    """photos: (photo_id, original_key) pairs. Ids are pre-generated by the
    caller so the storage key and the row can be built around the same id."""
    rows = [
        Photo(
            id=photo_id,
            event_id=event_id,
            uploader_id=uploader_id,
            original_key=original_key,
            status="awaiting_upload",
        )
        for photo_id, original_key in photos
    ]
    session.add_all(rows)
    await session.commit()
    return rows


async def mark_photo_queued(session: AsyncSession, photo: Photo) -> Photo:
    photo.status = "queued"
    await session.commit()
    return photo


async def get_gallery_photos(session: AsyncSession, event_id: uuid.UUID) -> list[Photo]:
    # Only photos that have finished processing (web/thumb generated) belong
    # in the gallery. Newest-first, backed by idx_photos_event_taken.
    stmt = (
        select(Photo)
        .where(
            Photo.event_id == event_id,
            Photo.web_key.isnot(None),
            Photo.thumb_key.isnot(None),
        )
        .order_by(Photo.taken_at.desc(), Photo.created_at.desc())
    )
    result = await session.execute(stmt)
    return list(result.scalars().all())


async def count_photos_by_status(session: AsyncSession, event_id: uuid.UUID) -> dict[str, int]:
    # Backed by idx_photos_event_status, which exists specifically for this
    # progress-polling query.
    stmt = (
        select(Photo.status, func.count())
        .where(Photo.event_id == event_id)
        .group_by(Photo.status)
    )
    result = await session.execute(stmt)
    return dict(result.all())
