"""initial schema

Revision ID: 82dabc4137c8
Revises: 
Create Date: 2026-07-15 01:12:44.337620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '82dabc4137c8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Autogenerate never emits these: it diffs tables/columns, not server-side
    # extensions. Needed before create_table for the CITEXT and Vector columns below.
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('events',
    sa.Column('host_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Text(), server_default='active', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'expired', 'purged')", name='ck_events_status'),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_events_expiry', 'events', ['expires_at'], unique=False, postgresql_where=sa.text("status = 'active'"))
    op.create_table('face_enrollments',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('selfie_key', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=False),
    sa.Column('quality_score', sa.REAL(), nullable=False),
    sa.Column('consented_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_face_enrollments_event_user')
    )
    op.create_index('idx_enrollments_event', 'face_enrollments', ['event_id'], unique=False)
    op.create_table('invitations',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('invite_token', sa.Text(), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.Text(), server_default='guest', nullable=False),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('host', 'guest')", name='ck_invitations_role'),
    sa.CheckConstraint("status IN ('pending', 'joined', 'revoked')", name='ck_invitations_status'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_invitations_event_user'),
    sa.UniqueConstraint('invite_token')
    )
    op.create_index('idx_invitations_event', 'invitations', ['event_id'], unique=False)
    op.create_table('photos',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('uploader_id', sa.UUID(), nullable=False),
    sa.Column('original_key', sa.Text(), nullable=False),
    sa.Column('web_key', sa.Text(), nullable=True),
    sa.Column('thumb_key', sa.Text(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), server_default='awaiting_upload', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('awaiting_upload', 'queued', 'processing', 'processed', 'failed')", name='ck_photos_status'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_photos_event_status', 'photos', ['event_id', 'status'], unique=False)
    op.create_index('idx_photos_event_taken', 'photos', ['event_id', sa.literal_column('taken_at DESC')], unique=False)
    op.create_table('faces',
    sa.Column('photo_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('bbox', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('det_score', sa.REAL(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True),
    sa.Column('crop_key', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_faces_event', 'faces', ['event_id'], unique=False)
    op.create_index('idx_faces_photo', 'faces', ['photo_id'], unique=False)
    op.create_table('photo_tags',
    sa.Column('photo_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('face_id', sa.UUID(), nullable=True),
    sa.Column('similarity', sa.REAL(), nullable=False),
    sa.Column('status', sa.Text(), server_default='confirmed', nullable=False),
    sa.Column('source', sa.Text(), server_default='auto', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('auto', 'guest_confirmed', 'host_action')", name='ck_photo_tags_source'),
    sa.CheckConstraint("status IN ('confirmed', 'pending_guest', 'rejected')", name='ck_photo_tags_status'),
    sa.ForeignKeyConstraint(['face_id'], ['faces.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('photo_id', 'user_id')
    )
    op.create_index('idx_tags_user', 'photo_tags', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tags_user', table_name='photo_tags')
    op.drop_table('photo_tags')
    op.drop_index('idx_faces_photo', table_name='faces')
    op.drop_index('idx_faces_event', table_name='faces')
    op.drop_table('faces')
    op.drop_index('idx_photos_event_taken', table_name='photos')
    op.drop_index('idx_photos_event_status', table_name='photos')
    op.drop_table('photos')
    op.drop_index('idx_invitations_event', table_name='invitations')
    op.drop_table('invitations')
    op.drop_index('idx_enrollments_event', table_name='face_enrollments')
    op.drop_table('face_enrollments')
    op.drop_index('idx_events_expiry', table_name='events', postgresql_where=sa.text("status = 'active'"))
    op.drop_table('events')
    op.drop_table('users')
    # ### end Alembic commands ###
    op.execute("DROP EXTENSION IF EXISTS vector")
    op.execute("DROP EXTENSION IF EXISTS citext")
